version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feedback_db
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"